apiVersion: v1
kind: Pod
metadata:
  name: ""
  generateName: polr-
spec:
  containers:
    - name: polr
      image: gcr.io/blissful-glass-144400/polr 
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: db.host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: db.user
        - name: DB_PASS
          valueFrom:
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: db.pass
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: db.database
        - name: APP_URL
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: app.url
        - name: APP_NAME
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: app.name
        - name: SETUP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: setup.password
        - name: REG_TYPE
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: reg.type
        - name: IP_METHOD
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: ip.method
        - name: PRIVATE
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: private
        - name: THEME
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: theme
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: admin.user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: admin.password
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: polrSecrets
              key: admin.email
  restartPolicy: Never

